apiVersion: apps/v1
kind: Deployment
metadata:
  name: emt-backend
  labels:
    app: emt
    tier: backend
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: emt
      tier: backend
  template:
    metadata:
      labels:
        app: emt
        tier: backend
    spec:
      containers:
        - name: backend
          image: docker.io/vasko117/backend:latest
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://emt-db:5432/emt 
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
      imagePullSecrets:
        - name: regcred 