apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: accomidations
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dmFzaWw=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: accomidations
data:
  POSTGRES_DB: emt

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: accomidations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vasko117/backend:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/emt
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          ports:
            - containerPort: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: accomidations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: vasko117/frontend:latest
          env:
            - name: REACT_APP_BACKEND_URL
              value: 'http://backend:9091/api'
          ports:
            - containerPort: 80
