version: '3.8'

services:
  backend:
    build: 
      context: ./vb
    ports:
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/emt
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=vasil
    depends_on:
      - db
    container_name: backend

  frontend:
    build:
      context: ./emt
    ports:
      - "80:80"
    depends_on:
      - backend
    
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: emt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vasil