apiVersion: apps/v1
kind: Deployment
metadata:
  name: emt-frontend
  labels:
    app: emt
    tier: frontend
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: emt
      tier: frontend
  template:
    metadata:
      labels:
        app: emt
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/vasko117/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: http://emt-backend:9091/api
      imagePullSecrets:
        - name: regcred  