apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: accomidations
spec:
  ports:
    - port: 5432
  selector:
    app: db

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: accomidations
spec:
  ports:
    - port: 9091
  selector:
    app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: accomidations
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: frontend
